[package]
name = "substitution"
authors = ["Lauri Gustafsson"]
description = "Encode and decipher substitution ciphers"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.1"
clap = { version = "3.1.6", features = ["derive"] }
rand = "0.8.4"
